name: the story of success
favicon: null
layout_spectrum: 0.9139785
typography_spectrum: 0.7849463
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'startegic marketing through story that leads to success '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1F1E1F'
    - '#5E6E87'
    - '#D8904B'
    - '#AB7865'
    - '#6E4130'
  brandStrength: 1
  lightness: 0.2078853
  saturation: 0.7419355
  rhythmicContrast: 1
purpose: []
