name: the story of success
favicon: null
layout_spectrum: 0.2408843762241304
typography_spectrum: 0.5388226211071014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8950449184048921
  lightness: 0.12094369763508439
  saturation: 0.2074195418972522
  rhythmicContrast: 0.08636248018592596
purpose: []
